title:            Bit Prepared
description:      Digito ergo sum, per un uso consapevole del digitale
logo:             agesci_logo.png
disqus_shortname: true
search:           true
email:            info@bitprepared.it

# Plugins
whitelist: []
gems:      ['jekyll-lunr-js-search', 'jekyll-picture-tag']

# output
encoding:         "utf-8"

# search
lunr_search:
  stopwords: "stopwords.txt"
  #ignorato??
  min_length: 3


# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
#url:              //localhost:4000
url:              //www.bitprepared.it

# Owner del sito
owner:
  name: Bit Prepared
  twitter: bitprepared
  github: bitprepared
  facebook: Bit-Prepared-1005896716166983

# Authors information
authors:
  yoghi:
    name: Stefano Tamagnini
    avatar: bio-photo.jpg
    email: stage@bitprepared.it
    # Social networking links used in footer. Update and remove as you like.
    twitter: yoghi
    facebook:
    github:
    stackexchange:
    linkedin:
    instagram:
    flickr:
    tumblr:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-34022989-3
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: News
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
  - title: Programmi
    url: /software/
  - title: Base Scout Costigiola
    url: http://costigiola.it
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:year/:month/:day/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    sass_dir: _sass
    style: :compressed

pages: ./_pages

picture:
  source: images/_fullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 960
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 640
        height: 480
      source_default:
        width: 250
        height: 250


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
