source 'https://rubygems.org'

gem 'jekyll', '3.3.0'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport', '4.2.9'
gem 'stringex'
gem 'font-awesome-sass'
gem 'sass'
gem 'jekyll-sass-converter'
gem 'mini_magick'
gem 'fastimage'
#gem 'jekyll-lunr-js-search', '2.0.0'
#gem 'therubyracer', '0.12.2'
#gem 'nokogiri', '1.6.0'
