source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'font-awesome-sass'
gem 'sass'
gem 'jekyll-sass-converter'
gem 'mini_magick'
gem 'jekyll-lunr-js-search'
gem 'fastimage'