name: Release Site

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      if: inputs.releaseVersion == ''
      id: date
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY-MM-DD"
    - name: Test with environment variables
      run: echo $TAG_NAME - $RELEASE_NAME
      env:
        TAG_NAME: tag-${{ steps.date.outputs.time }}
        RELEASE_NAME: release-${{ steps.date.outputs.time }}
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "_site/*"
        makeLatest: true
        tag: $TAG_NAME
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
